hydra:
  job:
    chdir: false
  run:
    dir: .

paths:
  train_data: ${oc.env:PWD}/data/train.csv
  test_data: ${oc.env:PWD}/data/test.csv
  outputs: model_outputs
  probabilities: probabilities
  forecasts: forecasts
  models: models

params:
  clear: true
  n_steps: 24
  feature: meantemp
  pdq: (5, 1, 0)
  seasonality: 365
